[build]
  base = "frontend"  # La carpeta donde se encuentra el frontend
  command = "npm run build"  # Comando para construir el frontend
  publish = "frontend/build"  # La carpeta que contiene el sitio construido

[functions]
  directory = "backend/netlify/functions"  # Carpeta donde se encuentran tus funciones

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
